---
services:
  web:
    container_name: 'web'
    build:
      context: "."
      dockerfile: "./Dockerfile.dev"
    command: >
      bash -c "poetry run alembic upgrade head &&
               poetry run hypercorn --bind 0.0.0.0:8000 --reload jinet.main:app"
    volumes:
      - "./:/jinet:rw"
    ports:
      - "5000:8000"
    environment:
      - "DATABASE_URI=postgresql+asyncpg://postgres:postgres@database/jinet"
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"
      - "AUTH0_DOMAIN=${AUTH0_DOMAIN}"
    depends_on:
      - "database"

  database:
    image: 'postgres:16.2'
    container_name: 'database'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=jinet'
...
