---
version: "3"

services:
  web:
    container_name: 'web'
    build: "./server"
    command: >
      bash -c "poetry run alembic upgrade head &&
               poetry run hypercorn --bind 0.0.0.0:8000 --reload jinet.main:app"
    volumes:
      - "./server:/jinet:rw"
    ports:
      - "8000:8000"
    environment:
      - "DATABASE_URI=postgresql+asyncpg://postgres:postgres@database/jinet"
    depends_on:
      - "database"

  database:
    image: 'postgres:16.2'
    container_name: 'database'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=jinet'
...
